### PR TITLE
JDK-8211302 - Drag and Drop on GTK3

### PR DESCRIPTION
**Pull request by tsayao**

### CODE REVIEW

**Comment by pankaj-bansal** [comment]
@tsayao  I am actively trying to solve this issue, but not able to make much progress. It will be great if you can help me by giving some pointers. I will try to solve this ASAP. I tested your patch. I do get some mouse move drags events sometime in beginning of dnd if I take the mouse outside and bring it inside the window, but then they stop. May be its time issue.
I don't know if you have tested this on gtk3.18 or lower, but our code seems to work fine there. So something has changed in gtk3.20. You ca test this by running Ubuntu 16.04 as it has gtk3.18 as default. One thing I noticed in your patch is that gdk_device_grab has been deprecated from 3.20 and gtk_seat_grab is preferred now. I tried that change, but did not make much difference.
https://developer.gnome.org/gdk3/stable/GdkDevice.html#gdk-device-grab

**Comment by tsayao** [comment]
@pankaj-bansal Let me explain the patch:

The problem is in gdk-device-grab function call. The gdk docs states that this function must grab de device from the GdkEvent:
https://developer.gnome.org/gdk3/stable/GdkDevice.html#gdk-device-grab

That's what I have changed. The function is deprecated, but we can't rely on 3.20 (unless we bundle GTK with openjfx).

**Still need to work on:**

This is missing on the patch: 
On  dnd_source_push_data(JNIEnv *env, jobject data, jint supported) there is a call to dnd_pointer_grab(NULL, NULL). This is wrong, we must pass the GdkEvent.

Cheers.

**Comment by pankaj-bansal** [comment]
ok, I can try to do that. I see that the GdkEvent is not present in dnd_source_push_data in any form. Can you tell me how are you planning to access it inside the function dnd_source_push_data to pass it to dnd_pointer_grab. I will complete that part and update you.

**Comment by tsayao** [comment]
@pankaj-bansal 

Did that, but does not work (makes sense tho hehe):

```
static void dnd_source_push_data(JNIEnv *env, jobject data, jint supported)
{
    GdkWindow *src_window = get_dnd_window();
    GList *targets;
    GdkDragContext *ctx;

    if (supported == 0) {
        return; // No supported actions, do nothing
    }

    targets = data_to_targets(env, data);

    data = env->NewGlobalRef(data);

    g_object_set_data_full(G_OBJECT(src_window), SOURCE_DND_DATA, data, clear_global_ref);
    g_object_set_data(G_OBJECT(src_window), SOURCE_DND_ACTIONS, (gpointer)translate_glass_action_to_gdk(supported));

    DragView::set_drag_view();

#ifdef GLASS_GTK3
    GdkDevice *device = gdk_device_manager_get_client_pointer(
                    gdk_display_get_device_manager(
                        gdk_display_get_default()));

    ctx = gdk_drag_begin_for_device(src_window, device, targets);
#else
    ctx = gdk_drag_begin(src_window, targets);
#endif

    g_list_free(targets);
    g_object_set_data(G_OBJECT(src_window), SOURCE_DND_CONTEXT, ctx);

#ifdef GLASS_GTK3
    gdk_device_grab(device, src_window, GDK_OWNERSHIP_NONE, FALSE,
                    GDK_ALL_EVENTS_MASK, NULL, GDK_CURRENT_TIME);
#else
    dnd_pointer_grab(NULL, NULL);
#endif

    is_dnd_owner = TRUE;
}
```

**Pull request closed without merging**
